#include <gtest/gtest.h>
#include "redcode/rust_bridge.h"

// This test suite verifies the connection between C++ and Rust.
TEST(FFIBridgeTest, CanCallRustFunction) {
    // This test calls the function that is implemented in the Rust crate.
    // The primary purpose is to ensure that the C++ code can successfully
    // link against and call the Rust library.
    // The Rust function will print a message to the console.
    // We use ASSERT_NO_THROW to confirm the function call itself doesn't cause a crash.

    // Redirect stdout to a buffer to check the output could be a future improvement.
    ASSERT_NO_THROW(hello_from_rust());
}

TEST(FFIBridgeTest, CanScheduleTrainingFromJson) {
    // This JSON string mimics a serialized TrainingConfig structure.
    // In a real application, this would be generated by a C++ JSON library.
    const char* json_config = R"json(
    {
      "model": {
        "id": "test_model_123",
        "layers": [
          {
            "PhiLinear": {
              "input_dim": 784,
              "output_dim": 128,
              "weights": { "id": 1, "shape": [784, 128] },
              "bias": { "id": 2, "shape": [128] }
            }
          },
          { "PhiActivation": null },
          { "Dropout": { "rate": 0.5 } }
        ],
        "config": {
          "learning_rate": 0.01
        },
        "metadata": {
          "properties": {
            "author": "Jules"
          }
        }
      },
      "optimizer": {},
      "scheduler": {},
      "quantization": {},
      "distributed": {}
    }
    )json";

    // Call the FFI function and assert that it returns a positive task ID on success.
    long long task_id = schedule_training_from_json(json_config);
    ASSERT_GT(task_id, 0);
}

TEST(FFIBridgeTest, FailsGracefullyOnImpossibleAllocation) {
    // This JSON requests an impossibly large amount of memory by setting
    // the learning_rate, which our mock allocation logic uses as the memory request.
    const char* json_config = R"json(
    {
      "model": {
        "id": "impossible_model",
        "layers": [],
        "config": { "learning_rate": 99999.0 },
        "metadata": { "properties": {} }
      },
      "optimizer": {}, "scheduler": {}, "quantization": {}, "distributed": {}
    }
    )json";

    long long task_id = schedule_training_from_json(json_config);
    // Expect the specific error code for resource allocation failure
    ASSERT_EQ(task_id, -10);
}
